#define yy_create_buffer ksm_clike__create_buffer
#define yy_delete_buffer ksm_clike__delete_buffer
#define yy_scan_buffer ksm_clike__scan_buffer
#define yy_scan_string ksm_clike__scan_string
#define yy_scan_bytes ksm_clike__scan_bytes
#define yy_flex_debug ksm_clike__flex_debug
#define yy_init_buffer ksm_clike__init_buffer
#define yy_flush_buffer ksm_clike__flush_buffer
#define yy_load_buffer_state ksm_clike__load_buffer_state
#define yy_switch_to_buffer ksm_clike__switch_to_buffer
#define yyin ksm_clike_in
#define yyleng ksm_clike_leng
#define yylex ksm_clike_lex
#define yyout ksm_clike_out
#define yyrestart ksm_clike_restart
#define yytext ksm_clike_text
#define yywrap ksm_clike_wrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
static yyconst short int yy_accept[197] =
    {   0,
        0,    0,   70,   68,   67,   67,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   53,   52,   68,   68,
       68,   51,   68,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   68,   32,    0,
       61,    0,    0,   50,   49,   41,   33,   46,   39,   35,
       42,   36,   43,   27,    0,   58,   40,   55,    0,    0,
       57,   52,    0,   59,   37,   29,   31,   30,   38,   51,
       51,   51,   47,   26,   51,   51,   51,   51,    6,   51,
       51,   51,   51,   51,    3,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   48,   34,    0,   66,

       66,   66,   66,   28,    0,   60,   56,   54,   57,    0,
       57,   44,   45,   51,   51,   51,   51,   51,   51,   51,
       51,    7,    1,   16,   51,   51,   51,   51,   51,   51,
       51,   51,   51,    2,   51,   51,   62,    0,    0,    0,
        0,   58,   51,   11,   14,   10,   51,    4,   51,   51,
       17,   51,   51,   51,   51,   51,   51,   51,   51,   13,
       51,    0,    0,    0,    9,   51,   51,   18,   51,   15,
       51,   51,   51,   51,   23,   51,    5,    0,    0,   65,
       19,   12,    8,   20,   25,   22,   51,   51,    0,   63,
       24,   51,    0,   21,   64,    0

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    1,    1,
        1,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   17,   17,   18,    1,   19,
       20,   21,   22,    1,   23,   24,   25,   26,   27,   26,
       28,   28,   29,   28,   28,   30,   28,   31,   28,   32,
       28,   28,   33,   28,   34,   28,   35,   36,   28,   28,
        1,   37,    1,   38,   28,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   28,   48,   49,   28,   50,
       51,   52,   28,   53,   54,   55,   56,   57,   58,   59,
       60,   61,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    4,    1,    1,
        1,    5,    3,    3,    3,    3,    3,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    1,    1,    3,    3,
        3,    3,    3,    3,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    1,    1,    1
    } ;

static yyconst short int yy_base[204] =
    {   0,
        0,    0,  289,  563,  563,  563,  267,   60,   29,  249,
       59,  246,   58,   60,   60,  243,   71,   76,   50,  241,
       62,   76,  196,   78,   83,   88,   86,   91,   96,   94,
      102,   99,  111,  104,  113,  133,  143,  105,  563,  123,
      563,    0,  136,  563,  563,  563,  563,  563,  563,  563,
      563,  563,  563,  563,  199,  160,  563,  164,  134,    0,
      177,  183,  198,  563,  163,  563,  563,  563,  151,  163,
      183,    0,  563,  184,  199,  200,  201,  207,  209,  210,
      215,  216,  221,  223,  226,  228,  229,  231,  234,  237,
      240,  250,  253,  258,  259,  266,  563,  563,  151,  563,

       72,  130,   84,  563,  280,  563,  221,    0,  300,  304,
      308,  563,  563,  287,  286,  281,  310,  313,  315,  318,
      320,  323,  326,  328,  338,  344,  345,  346,  347,  352,
      354,  353,  355,  360,  363,  362,  563,  138,  120,    0,
      372,  377,  377,  385,  388,  391,  394,  396,  397,  399,
      404,  405,  410,  412,  411,  418,  419,  413,  424,  426,
      427,  300,  426,   77,  434,  435,  442,  450,  453,  455,
      458,  461,  463,  464,  466,  469,  471,  231,  447,  563,
      476,  477,  479,  484,  486,  491,  492,  494,  370,  563,
      493,  499,  495,  502,  563,  563,  541,  544,  549,  554,

       99,  557,   86
    } ;

static yyconst short int yy_def[204] =
    {   0,
      196,    1,  196,  196,  196,  196,  196,  197,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  198,  196,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  196,  196,  197,
      196,  199,  200,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  201,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  198,
      198,  202,  196,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  196,  196,  199,  196,

      196,  196,  196,  196,  196,  196,  196,  201,  196,  196,
      196,  196,  196,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  196,  196,  196,  203,
      196,  196,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  196,  196,  203,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  196,  196,  196,
      198,  198,  198,  198,  198,  198,  198,  198,  196,  196,
      198,  198,  196,  198,  196,    0,  196,  196,  196,  196,

      196,  196,  196
    } ;

static yyconst short int yy_nxt[628] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   18,   18,    4,   19,   20,
       21,    4,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,    4,   23,   24,   25,
       26,   27,   28,   29,   22,   22,   30,   22,   31,   22,
       22,   22,   32,   33,   34,   35,   36,   37,   22,   22,
       22,    4,   38,    4,   41,   43,   47,   50,   65,   66,
       52,   55,   44,   56,   56,   56,   56,   51,   48,   53,
       54,   68,   69,   45,   58,   58,   58,   61,  164,   62,
       62,   62,   62,   71,   59,   71,   42,   72,  138,   72,

       71,  108,   63,   71,   72,   71,   60,   72,   71,   72,
       59,   71,   72,   71,  138,   72,   71,   72,   63,   71,
       72,   71,   64,   72,   97,   72,   76,   41,   71,   60,
       71,   74,   72,   77,   72,   75,   79,   85,   78,   80,
      180,   88,  163,   86,   82,  140,   83,  107,  107,   81,
       71,   84,   87,   99,   72,  137,   89,   90,  163,   42,
       71,  139,   93,   92,   72,   91,  101,   98,  102,  103,
      113,   94,  162,   56,   56,   56,   56,   58,   58,   58,
       71,  139,  112,   95,   72,  101,  105,   42,   96,  102,
      109,  109,  109,  109,   61,  162,   62,   62,   62,   62,

       71,   71,  105,   63,   72,   72,  106,  110,  110,   63,
      104,  111,  111,  111,  111,   73,   71,   71,   71,   63,
       72,   72,   72,   64,   71,   63,   71,   71,   72,   64,
       72,   72,   71,   71,  107,  107,   72,   72,   71,  116,
       71,  114,   72,   71,   72,   71,   71,   72,   71,   72,
       72,   71,   72,  115,   71,   72,  117,   71,   72,  189,
       67,   72,   57,  119,  118,   49,  121,   71,   46,  120,
       71,   72,  123,  122,   72,   71,   71,  189,  125,   72,
       72,  128,  124,   71,  127,  126,   39,   72,  196,  141,
      141,  196,  130,  142,  142,  142,  142,  129,   71,  132,

      196,  131,   72,   71,   71,  135,  133,   72,   72,  196,
      134,  196,  136,  109,  109,  109,  109,  111,  111,  111,
      111,  111,  111,  111,  111,  143,   63,   71,  144,  178,
       71,   72,   71,  145,   72,   71,   72,   71,  196,   72,
       71,   72,   63,   71,   72,   71,   64,   72,  178,   72,
      196,  146,  147,  196,   64,   71,  196,  148,  150,   72,
      149,   71,   71,   71,   71,   72,   72,   72,   72,   71,
       71,   71,   71,   72,   72,   72,   72,   71,  196,   71,
       71,   72,  151,   72,   72,  142,  142,  142,  142,  155,
      142,  142,  142,  142,   71,  154,  157,  153,   72,  152,

      193,  159,   71,  158,  160,   71,   72,  156,   71,   72,
      161,   71,   72,   71,   71,   72,   71,   72,   72,  193,
       72,   71,   71,  106,  165,   72,   72,   71,   71,   71,
       71,   72,   72,   72,   72,   71,   71,  196,  196,   72,
       72,   71,  166,   71,   71,   72,  196,   72,   72,  167,
      179,   71,   71,  168,  171,   72,   72,  169,  173,   71,
      174,  172,  175,   72,  170,  196,  179,   71,  176,  177,
       71,   72,   71,  190,   72,   71,   72,  181,   71,   72,
       71,   71,   72,   71,   72,   72,   71,   72,   71,  190,
       72,  182,   72,   71,   71,  196,   71,   72,   72,  184,

       72,   71,  183,   71,  185,   72,  187,   72,   71,   71,
       71,   71,   72,   72,   72,   72,   71,  186,  188,   71,
       72,  195,  196,   72,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  191,  192,  195,  196,  196,
      194,   40,   40,   40,   40,   40,   70,   70,   70,   99,
      196,   99,   99,   99,  100,  196,  100,  100,  100,   72,
      196,   72,    3,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196
    } ;

static yyconst short int yy_chk[628] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,    9,   11,   13,   19,   19,
       14,   15,    9,   15,   15,   15,   15,   13,   11,   14,
       14,   21,   21,    9,   17,   17,   17,   18,  203,   18,
       18,   18,   18,   22,   17,   24,    8,   22,  101,   24,

       25,  201,   18,   27,   25,   26,   17,   27,   28,   26,
       17,   30,   28,   29,  101,   30,   32,   29,   18,   31,
       32,   34,   18,   31,   38,   34,   26,   40,   33,   17,
       35,   24,   33,   26,   35,   25,   27,   30,   26,   28,
      164,   32,  139,   30,   29,  103,   29,   59,   59,   28,
       36,   29,   31,   99,   36,   99,   33,   33,  139,   40,
       37,  102,   35,   34,   37,   33,   43,   38,   43,   43,
       69,   36,  138,   56,   56,   56,   56,   58,   58,   58,
       70,  102,   65,   36,   70,   43,   56,   99,   37,   43,
       61,   61,   61,   61,   62,  138,   62,   62,   62,   62,

       71,   74,   56,   61,   71,   74,   56,   63,   63,   62,
       55,   63,   63,   63,   63,   23,   75,   76,   77,   61,
       75,   76,   77,   61,   78,   62,   79,   80,   78,   62,
       79,   80,   81,   82,  107,  107,   81,   82,   83,   77,
       84,   75,   83,   85,   84,   86,   87,   85,   88,   86,
       87,   89,   88,   76,   90,   89,   78,   91,   90,  178,
       20,   91,   16,   80,   79,   12,   82,   92,   10,   81,
       93,   92,   84,   83,   93,   94,   95,  178,   87,   94,
       95,   90,   86,   96,   89,   88,    7,   96,    3,  105,
      105,    0,   91,  105,  105,  105,  105,   90,  116,   93,

        0,   92,  116,  115,  114,   95,   93,  115,  114,    0,
       94,    0,   96,  109,  109,  109,  109,  110,  110,  110,
      110,  111,  111,  111,  111,  114,  109,  117,  115,  162,
      118,  117,  119,  116,  118,  120,  119,  121,    0,  120,
      122,  121,  109,  123,  122,  124,  109,  123,  162,  124,
        0,  117,  118,    0,  111,  125,    0,  119,  121,  125,
      120,  126,  127,  128,  129,  126,  127,  128,  129,  130,
      132,  131,  133,  130,  132,  131,  133,  134,    0,  136,
      135,  134,  125,  136,  135,  141,  141,  141,  141,  129,
      142,  142,  142,  142,  143,  128,  131,  127,  143,  126,

      189,  133,  144,  132,  135,  145,  144,  130,  146,  145,
      136,  147,  146,  148,  149,  147,  150,  148,  149,  189,
      150,  151,  152,  142,  143,  151,  152,  153,  155,  154,
      158,  153,  155,  154,  158,  156,  157,    0,    0,  156,
      157,  159,  147,  160,  161,  159,    0,  160,  161,  149,
      163,  165,  166,  150,  154,  165,  166,  152,  156,  167,
      157,  155,  158,  167,  153,    0,  163,  168,  159,  161,
      169,  168,  170,  179,  169,  171,  170,  166,  172,  171,
      173,  174,  172,  175,  173,  174,  176,  175,  177,  179,
      176,  167,  177,  181,  182,    0,  183,  181,  182,  171,

      183,  184,  169,  185,  172,  184,  174,  185,  186,  187,
      191,  188,  186,  187,  191,  188,  192,  173,  176,  194,
      192,  193,    0,  194,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  187,  188,  193,    0,    0,
      192,  197,  197,  197,  197,  197,  198,  198,  198,  199,
        0,  199,  199,  199,  200,    0,  200,  200,  200,  202,
        0,  202,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,

      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196,  196,  196,  196,
      196,  196,  196,  196,  196,  196,  196
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "clex.l"
#define INITIAL 0
#line 2 "clex.l"
/* Copyright (C) 2000 - 2001 Hangil Chang

   This file is part of KSM-Scheme, Kit for Scheme Manipulation Scheme.
   
   KSM-Scheme is free software; you can distribute it and/or modify it
   under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2, or (at your option)
   any later version.
  
   KSM-Scheme is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even implied warranty of MERCHANTABILITY
   or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public
   License for more details.

   You should have received a copy of the GNU General Public License
   along with KSM-Scheme; see the file COPYING. If not, write to the
   Free Software Foundation, 59 Temple Place, Suite 330, Boston,
   MA 02111 USA.                                                   */

#include "ksm.h"
#define YYSTYPE ksm_t
#include "parse.tab.h"
extern ksm_t ksm_clike_get_port(void);
extern int ksm_clike_get_token_save(void);
extern void ksm_clike_set_token_save(int);
extern ksm_t ksm_clike_get_lval_save(void);
extern void ksm_clike_set_lval_save(ksm_t lval);
extern int ksm_clike_yyempty;
extern ksm_t ksm_clike_port;
#define PORT ksm_clike_port
#define YY_DECL int ksm_clike_lex()
#define YY_INPUT(buf,result,max_size) \
  { \
    int c = ksm_port_getc(PORT); \
    result = (c == EOF) ? YY_NULL : (buf[0]=c, 1); \
  }
static int yywrap();
ksm_t ksm_clike_lval;
extern ksm_t ksm_clike_simple_string(void);
extern ksm_t ksm_clike_complex_string(void);

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 43 "clex.l"


	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 197 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 563 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "clex.l"
return FUN;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 45 "clex.l"
return VAR;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "clex.l"
return IF;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 47 "clex.l"
return ELSE;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 48 "clex.l"
return WHILE;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 49 "clex.l"
return DO;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 50 "clex.l"
return FOR;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "clex.l"
return RETURN;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 52 "clex.l"
return BREAK;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 53 "clex.l"
return COND;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 54 "clex.l"
return CASE;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 55 "clex.l"
return EXTERN;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 56 "clex.l"
return VOID;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 57 "clex.l"
return CHAR;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 58 "clex.l"
return SHORT;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 59 "clex.l"
return INT;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 60 "clex.l"
return LONG;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "clex.l"
return FLOAT;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "clex.l"
return DOUBLE;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 63 "clex.l"
return SIGNED;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "clex.l"
return UNSIGNED;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "clex.l"
return STRUCT;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "clex.l"
return UNION;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 67 "clex.l"
return TYPEDEF;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 68 "clex.l"
return SIZEOF;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 69 "clex.l"
return AS;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 70 "clex.l"
return ARROW;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 71 "clex.l"
return DOTS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "clex.l"
return LE;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 73 "clex.l"
return GE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 74 "clex.l"
return EQ;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 75 "clex.l"
return NE;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 76 "clex.l"
return AND;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "clex.l"
return OR;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "clex.l"
return INC;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "clex.l"
return DEC;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "clex.l"
return LSHIFT;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 81 "clex.l"
return RSHIFT;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 82 "clex.l"
return MUL_ASSIGN;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 83 "clex.l"
return DIV_ASSIGN;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 84 "clex.l"
return REM_ASSIGN;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 85 "clex.l"
return ADD_ASSIGN;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 86 "clex.l"
return SUB_ASSIGN;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 87 "clex.l"
return LSHIFT_ASSIGN;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 88 "clex.l"
return RSHIFT_ASSIGN;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 89 "clex.l"
return AND_ASSIGN;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 90 "clex.l"
return XOR_ASSIGN;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 91 "clex.l"
return OR_ASSIGN;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "clex.l"
ksm_clike_lval = ksm_true_object; return TRUE_OBJ;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 93 "clex.l"
ksm_clike_lval = ksm_false_object; return FALSE_OBJ;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 94 "clex.l"
return IDENT;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 95 "clex.l"
return DECIMAL_NUMBER;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 96 "clex.l"
return DECIMAL_NUMBER;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 97 "clex.l"
return HEX_NUMBER;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 98 "clex.l"
return OCTAL_NUMBER;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 99 "clex.l"
return BINARY_NUMBER;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 100 "clex.l"
return FLOAT_NUMBER;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 101 "clex.l"
return FLOAT_NUMBER;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 102 "clex.l"
return IMAGINARY_NUMBER;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "clex.l"
return IMAGINARY_NUMBER;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "clex.l"
return SIMPLE_STRING;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "clex.l"
return COMPLEX_STRING;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "clex.l"
return CHAR_SPACE;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "clex.l"
return CHAR_NEWLINE;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "clex.l"
return CHAR_UNICODE;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 109 "clex.l"
return CHAR;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 110 "clex.l"
/* ignore space */
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 111 "clex.l"
return ksm_clike_text[0];
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 112 "clex.l"
ECHO;
	YY_BREAK
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 197 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 197 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 196);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 112 "clex.l"

static int yywrap()
{
  return 1;
}

void ksm_clike_dummy()
{
  yyunput(0,0);
}

char ksm_clike_hold_char()
{
  return yy_hold_char;
}

YY_BUFFER_STATE ksm_clike_current_buffer(void)
{
  return yy_current_buffer;
}

ksm_t ksm_clike_simple_string(void)
{
  return ksm_make_string_n(yytext+1, yyleng-2);
}

static int sbuf_size;
static char *sbuf;

ksm_t ksm_clike_complex_string(void)
{
  int n, ch, nn;
  char *s, *d;

  n = yyleng - 2;
  if( sbuf_size < n ){
    if( sbuf )
      ksm_dispose(sbuf);
    sbuf_size = n;
    sbuf = ksm_alloc(sbuf_size);
  }
  s = yytext+1;
  d = sbuf;
  while( n-- > 0 ){
    ch = *s++;
    if( ch == '"' )
      break;
    if( ch == '\\' ){
      if( n <= 0 )
	ksm_error("can't happen in ksm_clike_complex_string");
      --n;
      ch = *s++;
      switch(ch){
      case '"': break;
      case 'n': ch = '\n'; break;
      case 'r': ch = '\r'; break;
      case 't': ch = '\t'; break;
      case '\\': ch = '\\'; break;
      case 'U':
	{
	  int trail, i, n;
	  char buf[3];

	  if( n <= 0 )
	    ksm_error("unexpected EOF while reading unicode");
	  ch = *s++;
	  --n;
	  if( ch != '{' )
	    ksm_error("can't read unicode: \\U%c\n", ch);
	  ch = 0;
	  while( 1 ){
	    if( n <= 0 )
	      ksm_error("unexpected EOF while reading unicode");
	    trail = *s++;
	    --n;
	    if( trail >= '0' && trail <= '9' ){
	      ch <<= 4;
	      ch += (trail - '0');
	    }
	    else if( trail >= 'a' && trail <= 'f' ){
	      ch <<= 4;
	      ch += (trail + 10 - 'a');
	    }
	    else if( trail >= 'A' && trail <= 'F' ){
	      ch <<= 4; 
	      ch += (trail + 10 - 'A');
	    }
	    else
	      break;
	  }
	  if( trail != '}' )
	    ksm_error("unexpected character while reading unicode: 0X%X", 
		      trail);
	  nn = ksm_utf8_from_ucs4(&buf[0], ch);
	  for(i=0;i<nn;++i)
	    *d++ = buf[i];
	  continue;
	}
      default: 
	*d++ = '\\';
	break;
      }
      *d++ = ch;
    }
    else
      *d++ = ch;
  }
  return ksm_make_string_n(sbuf, d-sbuf);
}

ksm_t ksm_clike_lex_char(void)
{
  return ksm_make_char(yytext[2]);
}

ksm_t ksm_clike_lex_unicode(void)
{
  int ch = 0, c;
  char *p, *q;
  
  p = yytext + 4;
  q = yytext + yyleng - 1;
  while( p < q ){
    c = *p++;
    ch *= 16;
    if( c >= '0' && c <= '9' )
      ch += c - '0';
    else if( c >= 'A' && c <= 'F' )
      ch += c - 'A' + 10;
    else if( c >= 'a' && c <= 'f' )
      ch += c - 'a' + 10;
    else
      ksm_error("can't happen in ksm_clike_lex_unicode");
  }
  return ksm_make_char(ch);
}

ksm_t ksm_clike_lex_ident(void)
{
  return ksm_make_key(yytext);
}

ksm_t ksm_clike_decimal_number(void)
{
  return ksm_string_to_exact(yytext, 10);
}

ksm_t ksm_clike_hex_number(void)
{
  return ksm_string_to_exact(yytext+2, 16);
}

ksm_t ksm_clike_octal_number(void)
{
  return ksm_string_to_exact(yytext+1, 8);
}

ksm_t ksm_clike_binary_number(void)
{
  return ksm_string_to_exact(yytext+2, 2);
}

ksm_t ksm_clike_float_number(void)
{
  return ksm_string_to_inexact(yytext);
}

ksm_t ksm_clike_imaginary_number(void)
{
  return ksm_string_to_inexact(yytext);
}
